### PR TITLE
Device Tracker, plus QOL fixes for default ports and SSL verify to allow disable if user chooses.

### PR DESCRIPTION
**Pull request by BongoEADGC6**
## Description:

**Related issue (if applicable):** fixes #<mycroft-homeassistant issue number goes here>

## Checklist:
  - [X] Travis is passing tests **Your PR cannot be merged unless tests pass**
  - [X] No PEP Bot Errors or Issues

### CODE REVIEW

**Comment by BongoEADGC6** [comment]
To explain further. 

The module required you to have `'portnum': 8123` in your config file, which is the default for home assistant. Seemed like a simple fix for usability.

Also, for my situation, I don't have certs in a way to allow requests to verify my certs like a hostname mismatch. So it allows a user to disable cert verification if they would like.

**Comment by btotharye** [comment]
Ok that works I'll test it out and as long as it all works fine for me to just verify I'll merge it in

**Comment by BongoEADGC6** [comment]
I found one mistake. line 88, I missed the `verify=self.verify` there.

**Comment by btotharye** [comment]
I'll test tonight and merge it in

**Pull request merged**
