### PR TITLE
Fix auto-application of websettings

### PR DESCRIPTION
**Pull request by nielstron**
## Description:
As far as I know, when the websettings change, the skill is not necessarily restarted. It doesn't need to be, but the settings have to be reset anyway.

A change in the local settings has to be forcibly applied after the websettings changed. This is all that this PR is meant for.

## Checklist:
  - [x] Code is Python 3.x compatible
  - [ ] Travis is passing tests **Your PR cannot be merged unless tests pass**
  - [ ] No PEP Bot Errors or Issues

### CODE REVIEW

**Comment by btotharye** [comment]
test this please

**Comment by btotharye** [comment]
@nielstron have you tested this, this is generating errors in my tests with this code.

https://jenkins.btotharye.com/job/home_assistant_skill/3/console

**Comment by btotharye** [comment]
test this please

**Comment by nielstron** [comment]
Sorry, my Mycroft does not work at the moment, so I won't be able to test this until in ~ 2-8 weeks

**Comment by nielstron** [comment]
Problem is already addressed in current master.

**Pull request closed without merging**
